const range = (prefix, from, to) =>
  Array.from({ length: to - from + 1 }, (_, i) => `${prefix}${from + i}`);

export const SECTIONS = [
  { id: 'panini',      name: 'We Are Panini',          emoji: '✨',   stickers: ['00'],              type: 'special' },
  { id: 'fwc_intro',   name: 'FIFA World Cup 2026',     emoji: '🏆',   stickers: range('FWC', 1, 8),  type: 'special' },
  { id: 'mex',         name: 'Mexico',                  iso: 'mx',     stickers: range('MEX', 1, 20), type: 'country' },
  { id: 'rsa',         name: 'South Africa',            iso: 'za',     stickers: range('RSA', 1, 20), type: 'country' },
  { id: 'kor',         name: 'Korea Republic',          iso: 'kr',     stickers: range('KOR', 1, 20), type: 'country' },
  { id: 'cze',         name: 'Czechia',                 iso: 'cz',     stickers: range('CZE', 1, 20), type: 'country' },
  { id: 'can',         name: 'Canada',                  iso: 'ca',     stickers: range('CAN', 1, 20), type: 'country' },
  { id: 'bih',         name: 'Bosnia Herzegovina',      iso: 'ba',     stickers: range('BIH', 1, 20), type: 'country' },
  { id: 'qat',         name: 'Qatar',                   iso: 'qa',     stickers: range('QAT', 1, 20), type: 'country' },
  { id: 'sui',         name: 'Switzerland',             iso: 'ch',     stickers: range('SUI', 1, 20), type: 'country' },
  { id: 'bra',         name: 'Brazil',                  iso: 'br',     stickers: range('BRA', 1, 20), type: 'country' },
  { id: 'mar',         name: 'Morocco',                 iso: 'ma',     stickers: range('MAR', 1, 20), type: 'country' },
  { id: 'hai',         name: 'Haiti',                   iso: 'ht',     stickers: range('HAI', 1, 20), type: 'country' },
  { id: 'sco',         name: 'Scotland',                iso: 'gb-sct', stickers: range('SCO', 1, 20), type: 'country' },
  { id: 'usa',         name: 'USA',                     iso: 'us',     stickers: range('USA', 1, 20), type: 'country' },
  { id: 'par',         name: 'Paraguay',                iso: 'py',     stickers: range('PAR', 1, 20), type: 'country' },
  { id: 'aus',         name: 'Australia',               iso: 'au',     stickers: range('AUS', 1, 20), type: 'country' },
  { id: 'tur',         name: 'Türkiye',                 iso: 'tr',     stickers: range('TUR', 1, 20), type: 'country' },
  { id: 'ger',         name: 'Germany',                 iso: 'de',     stickers: range('GER', 1, 20), type: 'country' },
  { id: 'cuw',         name: 'Curaçao',                 iso: 'cw',     stickers: range('CUW', 1, 20), type: 'country' },
  { id: 'civ',         name: "Côte d'Ivoire",           iso: 'ci',     stickers: range('CIV', 1, 20), type: 'country' },
  { id: 'ecu',         name: 'Ecuador',                 iso: 'ec',     stickers: range('ECU', 1, 20), type: 'country' },
  { id: 'ned',         name: 'Netherlands',             iso: 'nl',     stickers: range('NED', 1, 20), type: 'country' },
  { id: 'jpn',         name: 'Japan',                   iso: 'jp',     stickers: range('JPN', 1, 20), type: 'country' },
  { id: 'swe',         name: 'Sweden',                  iso: 'se',     stickers: range('SWE', 1, 20), type: 'country' },
  { id: 'tun',         name: 'Tunisia',                 iso: 'tn',     stickers: range('TUN', 1, 20), type: 'country' },
  { id: 'bel',         name: 'Belgium',                 iso: 'be',     stickers: range('BEL', 1, 20), type: 'country' },
  { id: 'egy',         name: 'Egypt',                   iso: 'eg',     stickers: range('EGY', 1, 20), type: 'country' },
  { id: 'irn',         name: 'IR Iran',                 iso: 'ir',     stickers: range('IRN', 1, 20), type: 'country' },
  { id: 'nzl',         name: 'New Zealand',             iso: 'nz',     stickers: range('NZL', 1, 20), type: 'country' },
  { id: 'esp',         name: 'Spain',                   iso: 'es',     stickers: range('ESP', 1, 20), type: 'country' },
  { id: 'cpv',         name: 'Cabo Verde',              iso: 'cv',     stickers: range('CPV', 1, 20), type: 'country' },
  { id: 'ksa',         name: 'Saudi Arabia',            iso: 'sa',     stickers: range('KSA', 1, 20), type: 'country' },
  { id: 'uru',         name: 'Uruguay',                 iso: 'uy',     stickers: range('URU', 1, 20), type: 'country' },
  { id: 'fra',         name: 'France',                  iso: 'fr',     stickers: range('FRA', 1, 20), type: 'country' },
  { id: 'sen',         name: 'Senegal',                 iso: 'sn',     stickers: range('SEN', 1, 20), type: 'country' },
  { id: 'irq',         name: 'Iraq',                    iso: 'iq',     stickers: range('IRQ', 1, 20), type: 'country' },
  { id: 'nor',         name: 'Norway',                  iso: 'no',     stickers: range('NOR', 1, 20), type: 'country' },
  { id: 'arg',         name: 'Argentina',               iso: 'ar',     stickers: range('ARG', 1, 20), type: 'country' },
  { id: 'alg',         name: 'Algeria',                 iso: 'dz',     stickers: range('ALG', 1, 20), type: 'country' },
  { id: 'aut',         name: 'Austria',                 iso: 'at',     stickers: range('AUT', 1, 20), type: 'country' },
  { id: 'jor',         name: 'Jordan',                  iso: 'jo',     stickers: range('JOR', 1, 20), type: 'country' },
  { id: 'por',         name: 'Portugal',                iso: 'pt',     stickers: range('POR', 1, 20), type: 'country' },
  { id: 'cod',         name: 'Congo DR',                iso: 'cd',     stickers: range('COD', 1, 20), type: 'country' },
  { id: 'uzb',         name: 'Uzbekistan',              iso: 'uz',     stickers: range('UZB', 1, 20), type: 'country' },
  { id: 'col',         name: 'Colombia',                iso: 'co',     stickers: range('COL', 1, 20), type: 'country' },
  { id: 'eng',         name: 'England',                 iso: 'gb-eng', stickers: range('ENG', 1, 20), type: 'country' },
  { id: 'cro',         name: 'Croatia',                 iso: 'hr',     stickers: range('CRO', 1, 20), type: 'country' },
  { id: 'gha',         name: 'Ghana',                   iso: 'gh',     stickers: range('GHA', 1, 20), type: 'country' },
  { id: 'pan',         name: 'Panama',                  iso: 'pa',     stickers: range('PAN', 1, 20), type: 'country' },
  { id: 'fwc_history', name: 'FIFA World Cup History',  emoji: '🏅',   stickers: range('FWC', 9, 19), type: 'special' },
  { id: 'coca_cola',   name: 'Coca-Cola',               emoji: '🥤',   stickers: range('CC', 1, 14),  type: 'special' },
];

export const ALL_STICKERS = SECTIONS.flatMap((s) => s.stickers);
export const TOTAL = ALL_STICKERS.length; // 994
