const range = (prefix, from, to) =>
  Array.from({ length: to - from + 1 }, (_, i) => `${prefix}${from + i}`);

export const SECTIONS = [
  { id: 'panini',      name: 'We Are Panini',          emoji: '✨',   stickers: ['00'],              type: 'special' },
  { id: 'fwc_intro',   name: 'FIFA World Cup 2026',     emoji: '🏆',   stickers: range('FWC', 1, 8),  type: 'special' },
  { id: 'mex',         name: 'Mexico',                  emoji: '🇲🇽',  stickers: range('MEX', 1, 20), type: 'country' },
  { id: 'rsa',         name: 'South Africa',            emoji: '🇿🇦',  stickers: range('RSA', 1, 20), type: 'country' },
  { id: 'kor',         name: 'Korea Republic',          emoji: '🇰🇷',  stickers: range('KOR', 1, 20), type: 'country' },
  { id: 'cze',         name: 'Czechia',                 emoji: '🇨🇿',  stickers: range('CZE', 1, 20), type: 'country' },
  { id: 'can',         name: 'Canada',                  emoji: '🇨🇦',  stickers: range('CAN', 1, 20), type: 'country' },
  { id: 'bih',         name: 'Bosnia Herzegovina',      emoji: '🇧🇦',  stickers: range('BIH', 1, 20), type: 'country' },
  { id: 'qat',         name: 'Qatar',                   emoji: '🇶🇦',  stickers: range('QAT', 1, 20), type: 'country' },
  { id: 'sui',         name: 'Switzerland',             emoji: '🇨🇭',  stickers: range('SUI', 1, 20), type: 'country' },
  { id: 'bra',         name: 'Brazil',                  emoji: '🇧🇷',  stickers: range('BRA', 1, 20), type: 'country' },
  { id: 'mar',         name: 'Morocco',                 emoji: '🇲🇦',  stickers: range('MAR', 1, 20), type: 'country' },
  { id: 'hai',         name: 'Haiti',                   emoji: '🇭🇹',  stickers: range('HAI', 1, 20), type: 'country' },
  { id: 'sco',         name: 'Scotland',                emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',  stickers: range('SCO', 1, 20), type: 'country' },
  { id: 'usa',         name: 'USA',                     emoji: '🇺🇸',  stickers: range('USA', 1, 20), type: 'country' },
  { id: 'par',         name: 'Paraguay',                emoji: '🇵🇾',  stickers: range('PAR', 1, 20), type: 'country' },
  { id: 'aus',         name: 'Australia',               emoji: '🇦🇺',  stickers: range('AUS', 1, 20), type: 'country' },
  { id: 'tur',         name: 'Türkiye',                 emoji: '🇹🇷',  stickers: range('TUR', 1, 20), type: 'country' },
  { id: 'ger',         name: 'Germany',                 emoji: '🇩🇪',  stickers: range('GER', 1, 20), type: 'country' },
  { id: 'cuw',         name: 'Curaçao',                 emoji: '🇨🇼',  stickers: range('CUW', 1, 20), type: 'country' },
  { id: 'civ',         name: "Côte d'Ivoire",           emoji: '🇨🇮',  stickers: range('CIV', 1, 20), type: 'country' },
  { id: 'ecu',         name: 'Ecuador',                 emoji: '🇪🇨',  stickers: range('ECU', 1, 20), type: 'country' },
  { id: 'ned',         name: 'Netherlands',             emoji: '🇳🇱',  stickers: range('NED', 1, 20), type: 'country' },
  { id: 'jpn',         name: 'Japan',                   emoji: '🇯🇵',  stickers: range('JPN', 1, 20), type: 'country' },
  { id: 'swe',         name: 'Sweden',                  emoji: '🇸🇪',  stickers: range('SWE', 1, 20), type: 'country' },
  { id: 'tun',         name: 'Tunisia',                 emoji: '🇹🇳',  stickers: range('TUN', 1, 20), type: 'country' },
  { id: 'bel',         name: 'Belgium',                 emoji: '🇧🇪',  stickers: range('BEL', 1, 20), type: 'country' },
  { id: 'egy',         name: 'Egypt',                   emoji: '🇪🇬',  stickers: range('EGY', 1, 20), type: 'country' },
  { id: 'irn',         name: 'IR Iran',                 emoji: '🇮🇷',  stickers: range('IRN', 1, 20), type: 'country' },
  { id: 'nzl',         name: 'New Zealand',             emoji: '🇳🇿',  stickers: range('NZL', 1, 20), type: 'country' },
  { id: 'esp',         name: 'Spain',                   emoji: '🇪🇸',  stickers: range('ESP', 1, 20), type: 'country' },
  { id: 'cpv',         name: 'Cabo Verde',              emoji: '🇨🇻',  stickers: range('CPV', 1, 20), type: 'country' },
  { id: 'ksa',         name: 'Saudi Arabia',            emoji: '🇸🇦',  stickers: range('KSA', 1, 20), type: 'country' },
  { id: 'uru',         name: 'Uruguay',                 emoji: '🇺🇾',  stickers: range('URU', 1, 20), type: 'country' },
  { id: 'fra',         name: 'France',                  emoji: '🇫🇷',  stickers: range('FRA', 1, 20), type: 'country' },
  { id: 'sen',         name: 'Senegal',                 emoji: '🇸🇳',  stickers: range('SEN', 1, 20), type: 'country' },
  { id: 'irq',         name: 'Iraq',                    emoji: '🇮🇶',  stickers: range('IRQ', 1, 20), type: 'country' },
  { id: 'nor',         name: 'Norway',                  emoji: '🇳🇴',  stickers: range('NOR', 1, 20), type: 'country' },
  { id: 'arg',         name: 'Argentina',               emoji: '🇦🇷',  stickers: range('ARG', 1, 20), type: 'country' },
  { id: 'alg',         name: 'Algeria',                 emoji: '🇩🇿',  stickers: range('ALG', 1, 20), type: 'country' },
  { id: 'aut',         name: 'Austria',                 emoji: '🇦🇹',  stickers: range('AUT', 1, 20), type: 'country' },
  { id: 'jor',         name: 'Jordan',                  emoji: '🇯🇴',  stickers: range('JOR', 1, 20), type: 'country' },
  { id: 'por',         name: 'Portugal',                emoji: '🇵🇹',  stickers: range('POR', 1, 20), type: 'country' },
  { id: 'cod',         name: 'Congo DR',                emoji: '🇨🇩',  stickers: range('COD', 1, 20), type: 'country' },
  { id: 'uzb',         name: 'Uzbekistan',              emoji: '🇺🇿',  stickers: range('UZB', 1, 20), type: 'country' },
  { id: 'col',         name: 'Colombia',                emoji: '🇨🇴',  stickers: range('COL', 1, 20), type: 'country' },
  { id: 'eng',         name: 'England',                 emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',  stickers: range('ENG', 1, 20), type: 'country' },
  { id: 'cro',         name: 'Croatia',                 emoji: '🇭🇷',  stickers: range('CRO', 1, 20), type: 'country' },
  { id: 'gha',         name: 'Ghana',                   emoji: '🇬🇭',  stickers: range('GHA', 1, 20), type: 'country' },
  { id: 'pan',         name: 'Panama',                  emoji: '🇵🇦',  stickers: range('PAN', 1, 20), type: 'country' },
  { id: 'fwc_history', name: 'FIFA World Cup History',  emoji: '🏅',   stickers: range('FWC', 9, 19), type: 'special' },
  { id: 'coca_cola',   name: 'Coca-Cola',               emoji: '🥤',   stickers: range('CC', 1, 14),  type: 'special' },
];

export const ALL_STICKERS = SECTIONS.flatMap((s) => s.stickers);
export const TOTAL = ALL_STICKERS.length; // 994
